### ISSUE TITLE
Magisk 14+

### ISSUE THREAD

**Issue by tasmo** [Nodens-/systemless-substratum-legacy#1]
Unfortunately v2 seems not to work with Magisk v14 anymore. Substratum can just be working in lagacy mode. Although Magisk shows the installed plugin without any errors.

Edit: There's a new module template available for Magisk 14+.
https://github.com/topjohnwu/magisk-module-template/commit/0708e652f49c8007e5c450010f500ef6c1205c74

**Comment by Clyybber** [comment]
Any progress on this specifically?
